const CONFIG = {
    titleWeb: "HELLO",
    introTitle: 'NP yangho',
    introDesc: `Không biết chị đã rảnh rỗi để chơi game hay chưa,
    btnIntro: '^^HiHi^^',
    title: 'Chơi đi nào',
    desc: 'Cao thủ đang chờ chị đó ',
    btnYes: 'ok',
    btnNo: 'chơi :3',
    question: 'Trên thế giới hơn 7 tỉ người mà em lại muốn chơi cùng chị',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Chơi thì chơi không chơi thì chơi',
    mess: 'Mình biết mà 🥰',
    messDesc: 'Tối nay 9h',
    btnAccept: 'Okiiiii lun <3',

